name: pcanvas
description: A portable canvas that can work in many platforms (Flutter, Web, Desktop, in-memory Image).
version: 1.1.1
homepage: https://github.com/gmpassos/pcanvas

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  image: ^4.3.0
  path_parsing: ^1.0.1
  xml: ^6.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
  dependency_validator: ^3.2.3
  coverage: ^1.10.0
