name: pcanvas
description: A portable canvas that can work in many platforms (Flutter, Web, Desktop, in-memory Image).
version: 1.0.6
homepage: https://github.com/gmpassos/pcanvas

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  image: ^4.0.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  dependency_validator: ^3.2.2
  coverage: ^1.6.1
