name: pcanvas
description: A portable canvas that can work in many platforms (Flutter, Web, Desktop, in-memory Image).
version: 2.0.0-beta.1
homepage: https://github.com/gmpassos/pcanvas

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  dio: ^5.8.0+1
  image: ^4.5.3
  path_parsing: ^1.1.0
  web_utils: ^1.0.12
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  dependency_validator: ^5.0.2
  coverage: ^1.11.1
