name: pcanvas
description: A portable canvas that can work in many platforms (Flutter, Web, Desktop, in-memory Image).
version: 1.0.5
homepage: https://github.com/gmpassos/pcanvas

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  image: ^3.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  dependency_validator: ^3.2.2
  coverage: ^1.6.1
