name: pcanvas
description: A portable canvas that can work in many platforms (Flutter, Web, Desktop, in-memory Image).
version: 1.1.0
homepage: https://github.com/gmpassos/pcanvas

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  dio: ^5.1.2
  image: ^4.0.17
  path_parsing: ^1.0.1
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
