name: pcanvas_example_web
description: Web example for package `pcanvas`.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  pcanvas: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.2
  lints: ^2.1.0

dependency_overrides:
  pcanvas:
    path: ../../
