name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Install dependencies
        run: dart pub get
      - name: dart format
        run: dart format -o none --set-exit-if-changed .
      - name: dart analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: dependency_validator
        run: dart run dependency_validator
      - name: Run tests (VM)
        run: dart test --platform vm
      - name: Run tests (Chrome)
        run: dart test --platform chrome
      - name: dart doc
        run: dart doc --dry-run
      - name: dart pub publish --dry-run
        run: dart pub publish --dry-run
